"""
DOCX export — generate Word document reports from analysis results.

Uses python-docx. All text is configurable via parameters.
"""

from pathlib import Path
from typing import Any, Dict, List, Optional
from datetime import datetime

import pandas as pd


def export_to_docx(
    analysis_results: Dict[str, Any],
    output_path: str,
    title: str = "Data Analysis Report",
    subtitle: str = "Comprehensive Analysis",
    brand_name: str = "DataPilot",
    visualisation_paths: Optional[Dict[str, Path]] = None,
    metrics: Optional[List[Dict[str, str]]] = None,
) -> str:
    """
    Export analysis results to Word document format.

    Args:
        analysis_results: Dict with analysis output (summary, sections, key_points, metrics).
        output_path: Where to save the DOCX.
        title: Report title.
        subtitle: Report subtitle.
        brand_name: Brand name for footer.
        visualisation_paths: Dict of {name: path} for chart images.
        metrics: List of {"label": ..., "value": ...} dicts for key metrics table.

    Returns:
        The output file path.
    """
    from docx import Document
    from docx.shared import Inches, Pt
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.enum.table import WD_TABLE_ALIGNMENT

    p = Path(output_path)
    p.parent.mkdir(parents=True, exist_ok=True)

    doc = Document()

    # Title
    heading = doc.add_heading(title, 0)
    heading.alignment = WD_ALIGN_PARAGRAPH.CENTER

    sub = doc.add_paragraph(subtitle)
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    doc.add_paragraph()

    # Executive Summary
    doc.add_heading('Executive Summary', level=1)

    summary_text = analysis_results.get("summary", "Analysis complete. See details below.")
    if isinstance(summary_text, str):
        doc.add_paragraph(summary_text)

    # Key Metrics
    report_metrics = metrics or analysis_results.get("metrics")
    if report_metrics:
        doc.add_heading('Key Metrics', level=1)

        table = doc.add_table(rows=len(report_metrics) + 1, cols=2)
        table.style = 'Table Grid'
        table.alignment = WD_TABLE_ALIGNMENT.CENTER

        # Header
        hdr = table.rows[0].cells
        hdr[0].text = "Metric"
        hdr[1].text = "Value"
        for cell in hdr:
            for paragraph in cell.paragraphs:
                for run in paragraph.runs:
                    run.bold = True

        for i, m in enumerate(report_metrics):
            row = table.rows[i + 1].cells
            row[0].text = m.get("label", "")
            row[1].text = str(m.get("value", ""))

        doc.add_paragraph()

    # Analysis Sections
    sections = analysis_results.get("sections", [])
    if sections:
        doc.add_heading('Detailed Analysis', level=1)

        for section in sections:
            heading_text = section.get("heading", "Analysis")
            doc.add_heading(heading_text, level=2)

            question = section.get("question")
            if question:
                q_para = doc.add_paragraph()
                run = q_para.add_run(f"Question: {question}")
                run.italic = True

            narrative = section.get("narrative", "")
            if narrative:
                doc.add_paragraph(narrative)

            key_points = section.get("key_points", [])
            for point in key_points:
                doc.add_paragraph(point, style='List Bullet')

            doc.add_paragraph()

    # Visualisations
    if visualisation_paths:
        doc.add_heading('Analysis Visualisations', level=1)

        for chart_name, chart_path in visualisation_paths.items():
            cp = Path(chart_path) if not isinstance(chart_path, Path) else chart_path
            if cp.exists():
                doc.add_heading(chart_name.replace('_', ' ').title(), level=2)
                doc.add_picture(str(cp), width=Inches(5.5))
                doc.add_paragraph()

    # Footer
    doc.add_paragraph()
    footer = doc.add_paragraph(f"Generated by {brand_name}")
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.save(str(p))
    return str(p)
