"""
DOCX export — generate Word document reports from analysis results.

Uses python-docx. All text is configurable via parameters.
"""

from pathlib import Path
from typing import Any, Dict, List, Optional
from datetime import datetime

import pandas as pd


def _add_page_number_footer(doc, brand_name: str) -> None:
    """Add page number fields to the document footer using XML field codes."""
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement
    from docx.shared import Pt
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    section = doc.sections[0]
    footer = section.footer
    footer.is_linked_to_previous = False

    paragraph = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # "Generated by {brand_name} | Page "
    run = paragraph.add_run(f"Generated by {brand_name} | Page ")
    run.font.size = Pt(8)

    # PAGE field
    fld_char_begin = OxmlElement('w:fldChar')
    fld_char_begin.set(qn('w:fldCharType'), 'begin')
    run_page = paragraph.add_run()
    run_page._r.append(fld_char_begin)

    instr_text = OxmlElement('w:instrText')
    instr_text.set(qn('xml:space'), 'preserve')
    instr_text.text = ' PAGE '
    run_instr = paragraph.add_run()
    run_instr._r.append(instr_text)

    fld_char_end = OxmlElement('w:fldChar')
    fld_char_end.set(qn('w:fldCharType'), 'end')
    run_end = paragraph.add_run()
    run_end._r.append(fld_char_end)

    # " of "
    run_of = paragraph.add_run(' of ')
    run_of.font.size = Pt(8)

    # NUMPAGES field
    fld_char_begin2 = OxmlElement('w:fldChar')
    fld_char_begin2.set(qn('w:fldCharType'), 'begin')
    run_np = paragraph.add_run()
    run_np._r.append(fld_char_begin2)

    instr_text2 = OxmlElement('w:instrText')
    instr_text2.set(qn('xml:space'), 'preserve')
    instr_text2.text = ' NUMPAGES '
    run_instr2 = paragraph.add_run()
    run_instr2._r.append(instr_text2)

    fld_char_end2 = OxmlElement('w:fldChar')
    fld_char_end2.set(qn('w:fldCharType'), 'end')
    run_end2 = paragraph.add_run()
    run_end2._r.append(fld_char_end2)


def export_to_docx(
    analysis_results: Dict[str, Any],
    output_path: str,
    title: str = "Data Analysis Report",
    subtitle: str = "Comprehensive Analysis",
    brand_name: str = "DataPilot",
    visualisation_paths: Optional[Dict[str, Path]] = None,
    metrics: Optional[List[Dict[str, str]]] = None,
) -> str:
    """
    Export analysis results to Word document format.

    Args:
        analysis_results: Dict with analysis output (summary, sections, key_points, metrics).
        output_path: Where to save the DOCX.
        title: Report title.
        subtitle: Report subtitle.
        brand_name: Brand name for footer.
        visualisation_paths: Dict of {name: path} for chart images.
        metrics: List of {"label": ..., "value": ...} dicts for key metrics table.

    Returns:
        The output file path.
    """
    from docx import Document
    from docx.shared import Inches, Pt
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.enum.table import WD_TABLE_ALIGNMENT

    p = Path(output_path)
    p.parent.mkdir(parents=True, exist_ok=True)

    doc = Document()

    # Add page number footer
    _add_page_number_footer(doc, brand_name)

    # Title
    heading = doc.add_heading(title, 0)
    heading.alignment = WD_ALIGN_PARAGRAPH.CENTER

    sub = doc.add_paragraph(subtitle)
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    doc.add_paragraph()

    # Executive Summary
    doc.add_heading('Executive Summary', level=1)

    summary_text = analysis_results.get("summary", "Analysis complete. See details below.")
    if isinstance(summary_text, str):
        doc.add_paragraph(summary_text)

    # Key Metrics (with page break before)
    report_metrics = metrics or analysis_results.get("metrics")
    if report_metrics:
        doc.add_page_break()
        doc.add_heading('Key Metrics', level=1)

        table = doc.add_table(rows=len(report_metrics) + 1, cols=2)
        table.style = 'Table Grid'
        table.alignment = WD_TABLE_ALIGNMENT.CENTER

        # Header
        hdr = table.rows[0].cells
        hdr[0].text = "Metric"
        hdr[1].text = "Value"
        for cell in hdr:
            for paragraph in cell.paragraphs:
                for run in paragraph.runs:
                    run.bold = True

        for i, m in enumerate(report_metrics):
            row = table.rows[i + 1].cells
            row[0].text = m.get("label", "")
            row[1].text = str(m.get("value", ""))

        doc.add_paragraph()

    # Analysis Sections (with page break before)
    sections = analysis_results.get("sections", [])
    section_skills_with_charts = set()
    if sections:
        doc.add_page_break()
        doc.add_heading('Detailed Analysis', level=1)

        for section in sections:
            heading_text = section.get("heading", "Analysis")
            doc.add_heading(heading_text, level=2)

            question = section.get("question")
            if question:
                q_para = doc.add_paragraph()
                run = q_para.add_run(f"Question: {question}")
                run.italic = True

            narrative = section.get("narrative", "")
            if narrative:
                doc.add_paragraph(narrative)

            key_points = section.get("key_points", [])
            for point in key_points:
                doc.add_paragraph(point, style='List Bullet')

            # Inline chart for this section
            skill = section.get("skill", "")
            if visualisation_paths and skill in visualisation_paths:
                cp = Path(visualisation_paths[skill]) if not isinstance(visualisation_paths[skill], Path) else visualisation_paths[skill]
                if cp.exists():
                    section_skills_with_charts.add(skill)
                    doc.add_picture(str(cp), width=Inches(5.5))

            doc.add_paragraph()

    # Catch-all for unmatched charts
    if visualisation_paths:
        unmatched = {k: v for k, v in visualisation_paths.items() if k not in section_skills_with_charts}
        if unmatched:
            doc.add_heading('Additional Visualisations', level=1)

            for chart_name, chart_path in unmatched.items():
                cp = Path(chart_path) if not isinstance(chart_path, Path) else chart_path
                if cp.exists():
                    doc.add_heading(chart_name.replace('_', ' ').title(), level=2)
                    doc.add_picture(str(cp), width=Inches(5.5))
                    doc.add_paragraph()

    doc.save(str(p))
    return str(p)
