"""
PDF export — generate PDF reports from analysis results.

Uses reportlab. All text is configurable via parameters (no hardcoded brand/domain).
"""

from datetime import datetime
from pathlib import Path
from typing import Any


def _make_numbered_canvas_class(brand_name="DataPilot"):
    """Create a Canvas subclass that draws page-number footers on every page.

    Returns a class (not an instance) suitable for passing as ``canvasmaker``
    to ``SimpleDocTemplate.build()``.  The class inherits directly from
    reportlab's ``Canvas`` so all platypus machinery works correctly.
    """
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.units import inch
    from reportlab.pdfgen.canvas import Canvas as _Canvas

    class _NumberedCanvas(_Canvas):

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self._saved_page_states = []

        def showPage(self):
            self._saved_page_states.append(dict(self.__dict__))
            self._startPage()

        def save(self):
            total = len(self._saved_page_states)
            for i, state in enumerate(self._saved_page_states):
                self.__dict__.update(state)
                self._draw_footer(i + 1, total)
                super().showPage()
            super().save()

        def _draw_footer(self, page_num, total_pages):
            self.saveState()
            self.setFont("Helvetica", 8)
            footer_text = f"Generated by {brand_name} | Page {page_num} of {total_pages}"
            self.drawCentredString(letter[0] / 2, 0.5 * inch, footer_text)
            self.restoreState()

    return _NumberedCanvas


def export_to_pdf(
    analysis_results: dict[str, Any],
    output_path: str,
    title: str = "Data Analysis Report",
    subtitle: str = "Comprehensive Analysis",
    brand_name: str = "DataPilot",
    visualisation_paths: dict[str, Path] | None = None,
    metrics: list[dict[str, str]] | None = None,
) -> str:
    """
    Export analysis results to PDF format using reportlab.

    Args:
        analysis_results: Dict with analysis output (summary, sections, key_points, metrics).
        output_path: Where to save the PDF.
        title: Report title.
        subtitle: Report subtitle.
        brand_name: Brand name for footer.
        visualisation_paths: Dict of {name: path} for chart images.
        metrics: List of {"label": ..., "value": ...} dicts for key metrics table.

    Returns:
        The output file path.
    """
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_CENTER
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        Image,
        ListFlowable,
        ListItem,
        PageBreak,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    p = Path(output_path)
    p.parent.mkdir(parents=True, exist_ok=True)

    doc = SimpleDocTemplate(
        str(p),
        pagesize=letter,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=72,
    )

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        name='Title2',
        parent=styles['Heading1'],
        fontSize=24,
        spaceAfter=30,
        alignment=TA_CENTER,
    ))
    styles.add(ParagraphStyle(
        name='Subtitle',
        parent=styles['Normal'],
        fontSize=14,
        spaceAfter=12,
        alignment=TA_CENTER,
        textColor=colors.grey,
    ))
    styles.add(ParagraphStyle(
        name='SectionBody',
        parent=styles['Normal'],
        fontSize=10,
        spaceAfter=8,
        leading=14,
    ))
    styles.add(ParagraphStyle(
        name='TOCEntry',
        parent=styles['Normal'],
        fontSize=12,
        spaceAfter=6,
        leading=16,
    ))

    story = []

    # --- Title page ---
    story.append(Spacer(1, 2 * inch))
    story.append(Paragraph(title, styles['Title2']))
    story.append(Paragraph(subtitle, styles['Subtitle']))
    story.append(Spacer(1, 0.5 * inch))
    story.append(Paragraph(
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        styles['Subtitle'],
    ))
    story.append(PageBreak())

    # --- Table of Contents ---
    story.append(Paragraph("Table of Contents", styles['Heading1']))
    story.append(Spacer(1, 12))
    toc_items = ["Executive Summary", "Key Metrics", "Detailed Analysis"]
    sections = analysis_results.get("sections", [])
    for section in sections:
        heading = section.get("heading", "Analysis")
        toc_items.append(f"    {heading}")
    if visualisation_paths:
        # Check for unmatched charts
        section_skills = {s.get("skill", "") for s in sections}
        unmatched = {k: v for k, v in visualisation_paths.items() if k not in section_skills}
        if unmatched:
            toc_items.append("Additional Visualisations")
    for item in toc_items:
        story.append(Paragraph(item, styles['TOCEntry']))
    story.append(PageBreak())

    # --- Executive Summary ---
    story.append(Paragraph("Executive Summary", styles['Heading1']))
    story.append(Spacer(1, 12))

    summary_text = analysis_results.get("summary", "Analysis complete. See details below.")
    if isinstance(summary_text, str):
        # Cap at ~500 words for 1 page
        words = summary_text.split()
        if len(words) > 500:
            summary_text = " ".join(words[:500]) + "..."
        story.append(Paragraph(summary_text, styles['SectionBody']))
    story.append(PageBreak())

    # --- Key Metrics Table ---
    report_metrics = metrics or analysis_results.get("metrics")
    if report_metrics:
        story.append(Paragraph("Key Metrics", styles['Heading1']))
        story.append(Spacer(1, 12))

        metrics_data = [["Metric", "Value"]]
        for m in report_metrics:
            metrics_data.append([m.get("label", ""), str(m.get("value", ""))])

        metrics_table = Table(metrics_data, colWidths=[3 * inch, 2 * inch])
        metrics_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#3498db')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#ecf0f1')),
            ('GRID', (0, 0), (-1, -1), 1, colors.white),
            ('FONTSIZE', (0, 1), (-1, -1), 10),
            ('TOPPADDING', (0, 1), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 1), (-1, -1), 8),
        ]))
        story.append(metrics_table)
        story.append(PageBreak())

    # --- Detailed Analysis with inline charts ---
    section_skills_with_charts = set()
    if sections:
        story.append(Paragraph("Detailed Analysis", styles['Heading1']))
        story.append(Spacer(1, 12))

        for section in sections:
            heading = section.get("heading", "Analysis")
            story.append(Paragraph(heading, styles['Heading2']))
            story.append(Spacer(1, 6))

            question = section.get("question")
            if question:
                story.append(Paragraph(
                    f"<i>Question: {question}</i>",
                    styles['SectionBody'],
                ))
                story.append(Spacer(1, 4))

            narrative = section.get("narrative", "")
            if narrative:
                story.append(Paragraph(narrative, styles['SectionBody']))
                story.append(Spacer(1, 6))

            key_points = section.get("key_points", [])
            if key_points:
                items = [
                    ListItem(Paragraph(point, styles['SectionBody']))
                    for point in key_points
                ]
                story.append(ListFlowable(items, bulletType='bullet', start=''))
                story.append(Spacer(1, 6))

            # Inline chart for this section
            skill = section.get("skill", "")
            if visualisation_paths and skill in visualisation_paths:
                cp = Path(visualisation_paths[skill]) if not isinstance(visualisation_paths[skill], Path) else visualisation_paths[skill]
                if cp.exists():
                    section_skills_with_charts.add(skill)
                    img = Image(str(cp), width=5.5 * inch, height=3.5 * inch)
                    story.append(img)
                    story.append(Spacer(1, 12))

            story.append(Spacer(1, 12))

    # --- Additional Visualisations (unmatched charts) ---
    if visualisation_paths:
        unmatched = {k: v for k, v in visualisation_paths.items() if k not in section_skills_with_charts}
        if unmatched:
            story.append(PageBreak())
            story.append(Paragraph("Additional Visualisations", styles['Heading1']))
            story.append(Spacer(1, 12))

            for chart_name, chart_path in unmatched.items():
                cp = Path(chart_path) if not isinstance(chart_path, Path) else chart_path
                if cp.exists():
                    story.append(Paragraph(
                        chart_name.replace('_', ' ').title(),
                        styles['Heading3'],
                    ))
                    story.append(Spacer(1, 6))
                    img = Image(str(cp), width=5.5 * inch, height=3.5 * inch)
                    story.append(img)
                    story.append(Spacer(1, 24))

    canvas_cls = _make_numbered_canvas_class(brand_name)
    doc.build(story, canvasmaker=canvas_cls)
    return str(p)
